### ISSUE TITLE
Create classes and test files for s1, s2, s3

### ISSUE THREAD

**Issue by ahr5** [scp756-221/term-project-angelababy#9]
For example create a playlist class that will have create/delete etc functions and write tests for it.

**Comment by mufeng121** [comment]
Test codes finished for s1, s2, s3. There seems to be a bug in s3 _delete_song_from_playlist()_. Have merged the recent main branch into service_test. Once the bug is fixed I could merge service_test branch into main branch.

**Comment by mufeng121** [comment]
Done with service tests and have updated it in main branch.
